# Generated by Django 6.1 on 2026-09-01 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CONGRESO_NACIONAL', 'Congreso Nacional'), ('CONGRESO_INTERNACIONAL', 'Congreso Internacional'), ('COLOQUIO', 'Coloquio / Simposio')], max_length=40, verbose_name='tipo de evento')),
                ('nombre_evento', models.CharField(max_length=255, verbose_name='nombre del evento')),
                ('titulo_ponencia', models.CharField(max_length=255, verbose_name='título de la ponencia')),
                ('fecha_presentacion', models.DateField(db_index=True, verbose_name='fecha de presentación')),
                ('sede_lugar', models.CharField(max_length=255, verbose_name='sede o lugar')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('HIBRIDA', 'Híbrida')], default='PRESENCIAL', max_length=20, verbose_name='modalidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'evento académico',
                'verbose_name_plural': 'eventos académicos',
                'ordering': ['-fecha_presentacion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtherProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('SOFTWARE', 'Desarrollo de Software'), ('PROTOTIPO', 'Prototipo Físico / Industrial'), ('PATENTE', 'Propiedad Intelectual / Patente'), ('BASE_DATOS', 'Base de Datos de Investigación'), ('OTRO', 'Otro')], max_length=30, verbose_name='tipo de producto')),
                ('titulo', models.CharField(max_length=255, verbose_name='título del producto')),
                ('descripcion', models.TextField(verbose_name='descripción y características')),
                ('fecha_registro', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'otro producto académico',
                'verbose_name_plural': 'otros productos académicos',
                'ordering': ['-fecha_registro', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('autores_texto', models.TextField(help_text='Lista de autores en formato APA o IEEE', verbose_name='autores')),
                ('tipo', models.CharField(choices=[('ARTICULO_JCR', 'Artículo JCR / Scopus'), ('ARTICULO_CONACYT', 'Artículo Conacyt / Índice Nacional'), ('CAPITULO_LIBRO', 'Capítulo de Libro'), ('OTRO', 'Otro')], max_length=30, verbose_name='tipo de publicación')),
                ('revista_editorial', models.CharField(max_length=255, verbose_name='revista o editorial')),
                ('estado', models.CharField(choices=[('PREPARACION', 'En Preparación'), ('ENVIADO', 'Enviado'), ('EN_REVISION', 'En Revisión'), ('ACEPTADO', 'Aceptado'), ('PUBLICADO', 'Publicado')], default='PREPARACION', max_length=30, verbose_name='estado')),
                ('fecha_publicacion', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de publicación')),
                ('doi_url', models.CharField(blank=True, default='', max_length=500, verbose_name='DOI o URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
                'ordering': ['-fecha_publicacion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_receptora', models.CharField(max_length=255, verbose_name='institución receptora')),
                ('pais', models.CharField(max_length=100, verbose_name='país')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de finalización')),
                ('responsable_estancia', models.CharField(max_length=255, verbose_name='responsable / investigador anfitrión')),
                ('objetivos', models.TextField(blank=True, default='', verbose_name='objetivos de la estancia')),
                ('resultados', models.TextField(blank=True, default='', verbose_name='resultados obtenidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'estancia de investigación',
                'verbose_name_plural': 'estancias de investigación',
                'ordering': ['-fecha_inicio', '-created_at'],
            },
        ),
    ]
