# Generated by Django 6.1 on 2026-09-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_output', '0001_initial'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicevent',
            name='evidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_events', to='evidence.evidence', verbose_name='evidencia'),
        ),
    ]
