# Generated by Django 6.1 on 2026-09-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_output', '0002_initial'),
        ('evidence', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicevent',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_events', to='students.semester', verbose_name='semestre'),
        ),
        migrations.AddField(
            model_name='academicevent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_events', to='students.student', verbose_name='estudiante'),
        ),
        migrations.AddField(
            model_name='otherproduct',
            name='evidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_products', to='evidence.evidence', verbose_name='evidencia'),
        ),
        migrations.AddField(
            model_name='otherproduct',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_products', to='students.semester', verbose_name='semestre'),
        ),
        migrations.AddField(
            model_name='otherproduct',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_products', to='students.student', verbose_name='estudiante'),
        ),
        migrations.AddField(
            model_name='publication',
            name='evidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='evidence.evidence', verbose_name='evidencia'),
        ),
        migrations.AddField(
            model_name='publication',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='students.semester', verbose_name='semestre'),
        ),
        migrations.AddField(
            model_name='publication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='students.student', verbose_name='estudiante'),
        ),
        migrations.AddField(
            model_name='researchstay',
            name='evidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_stays', to='evidence.evidence', verbose_name='evidencia'),
        ),
        migrations.AddField(
            model_name='researchstay',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_stays', to='students.semester', verbose_name='semestre'),
        ),
        migrations.AddField(
            model_name='researchstay',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_stays', to='students.student', verbose_name='estudiante'),
        ),
    ]
