# Generated by Django 6.0.5 on 2026-09-09 15:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('STUDENT', 'Estudiante'), ('TUTOR', 'Tutor'), ('COMMITTEE_MEMBER', 'Miembro del comité'), ('PROGRAM_COORDINATOR', 'Coordinador del programa'), ('ACADEMIC_ADMIN', 'Administrador académico'), ('SYSTEM_ADMIN', 'Administrador del sistema')], default='STUDENT', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('CONCLUIDO', 'Concluido'), ('VENCIDO', 'Vencido')], db_index=True, default='PENDIENTE', max_length=20)),
                ('fecha_conclusion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agreements', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agreements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('comentario', models.TextField(blank=True, default='')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='nexus.agreement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ARCHIVO_LOCAL', 'Archivo local'), ('ENLACE_DOI', 'Enlace DOI')], db_index=True, default='ARCHIVO_LOCAL', max_length=20)),
                ('actividad_tipo', models.CharField(db_index=True, default='OTRO', max_length=20)),
                ('actividad_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'docx', 'zip'])])),
                ('enlace_url', models.CharField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('fecha_carga', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='nexus.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('programa_doctoral', models.CharField(default='Doctorado en Ciencias', max_length=255)),
                ('fecha_ingreso', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('cohorte', models.CharField(db_index=True, max_length=20)),
                ('estatus_activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='nexus.student'),
        ),
        migrations.CreateModel(
            name='ResearchStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institucion_receptora', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField()),
                ('responsable_estancia', models.CharField(max_length=255)),
                ('objetivos', models.TextField(blank=True, default='')),
                ('resultados', models.TextField(blank=True, default='')),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.evidence')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.student')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('autores_texto', models.TextField()),
                ('tipo', models.CharField(max_length=30)),
                ('revista_editorial', models.CharField(max_length=255)),
                ('estado', models.CharField(default='PREPARACION', max_length=30)),
                ('fecha_publicacion', models.DateField(blank=True, db_index=True, null=True)),
                ('doi_url', models.CharField(blank=True, default='', max_length=500)),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.evidence')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_producto', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.evidence')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='nexus.student'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='nexus.student'),
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_evento', models.CharField(max_length=40)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('titulo_ponencia', models.CharField(max_length=255)),
                ('fecha_presentacion', models.DateField(db_index=True)),
                ('sede_lugar', models.CharField(max_length=255)),
                ('modalidad', models.CharField(default='PRESENCIAL', max_length=20)),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.evidence')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_comite', models.CharField(choices=[('ASESOR_PRINCIPAL', 'Asesor principal'), ('COASESOR', 'Coasesor'), ('VOCAL', 'Vocal'), ('SECRETARIO', 'Secretario')], max_length=30)),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_assignments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='nexus.student')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_avance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('componentes_json', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_registro', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_thesis_progresses', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_progresses', to='nexus.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_progresses', to='nexus.student')),
            ],
        ),
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion', models.DateField(db_index=True)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('HIBRIDA', 'Híbrida')], default='PRESENCIAL', max_length=20)),
                ('resumen', models.TextField()),
                ('proxima_reunion_fecha', models.DateField(blank=True, null=True)),
                ('proxima_reunion_notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_tutoring_sessions', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions', to='nexus.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions', to='nexus.student')),
            ],
        ),
        migrations.CreateModel(
            name='TutoringParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_sesion', models.CharField(max_length=30)),
                ('asistencia', models.BooleanField(default=True)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_attendances', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='nexus.tutoringsession')),
            ],
        ),
        migrations.CreateModel(
            name='TutoringObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_revisado', models.CharField(blank=True, default='', max_length=255)),
                ('observaciones_detalladas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_observations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='nexus.tutoringsession')),
            ],
        ),
        migrations.AddField(
            model_name='agreement',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='nexus.tutoringsession'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('student', 'numero'), name='unique_student_semester'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='semester_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='researchstay',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='research_stay_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='academiccommittee',
            constraint=models.UniqueConstraint(fields=('student', 'user', 'rol_comite'), name='unique_student_user_committee_role'),
        ),
        migrations.AddConstraint(
            model_name='tutoringparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_session_participant'),
        ),
    ]
