# Generated by Django 6.0.2 on 2026-09-14 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0002_adminauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccommittee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', related_query_name='committee_relationships', to='nexus.student'),
        ),
    ]
