# Generated by Django 6.0.2 on 2026-09-14 02:30

from django.db import migrations, models


def migrate_vocal_and_secretary(apps, schema_editor):
    AcademicCommittee = apps.get_model('nexus', 'AcademicCommittee')
    AcademicCommittee.objects.filter(rol_comite__in=['VOCAL', 'SECRETARIO']).update(rol_comite='MIEMBRO_COMITE')


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0003_alter_academiccommittee_student'),
    ]

    operations = [
        migrations.RunPython(migrate_vocal_and_secretary, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='academiccommittee',
            name='rol_comite',
            field=models.CharField(choices=[('ASESOR_PRINCIPAL', 'Asesor principal'), ('COASESOR', 'Coasesor'), ('MIEMBRO_COMITE', 'Miembro del comité')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricula',
            field=models.CharField(db_index=True, max_length=9, unique=True),
        ),
    ]
