# Generated by Django 6.0.2 on 2026-09-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0004_alter_academiccommittee_rol_comite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grammatical_gender',
            field=models.CharField(choices=[('MASCULINE', 'Masculino'), ('FEMININE', 'Femenino'), ('NEUTRAL', 'Neutral'), ('UNSPECIFIED', 'No especificado')], default='UNSPECIFIED', max_length=20),
        ),
    ]
