# Generated by Django 6.1.1 on 2026-09-15 00:21

import django.db.models.functions.text
from django.db import migrations, models


def normalize_matriculas(apps, schema_editor):
    Student = apps.get_model('nexus', 'Student')
    seen = set()
    for student in Student.objects.all().iterator():
        normalized = student.matricula.strip().upper()
        if normalized in seen:
            raise RuntimeError(f'Matrícula duplicada al normalizar: {normalized}')
        seen.add(normalized)
        if student.matricula != normalized:
            student.matricula = normalized
            student.save(update_fields=['matricula'])


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0005_add_grammatical_gender_to_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricula',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.RunPython(normalize_matriculas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('matricula'), name='unique_student_matricula_ci'),
        ),
    ]
