# Generated by Django 6.1.1 on 2026-09-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0007_remodel_academic_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringparticipant',
            name='rol_en_sesion',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('ASESOR_PRINCIPAL', 'Asesor principal'), ('COASESOR', 'Coasesor'), ('MIEMBRO_COMITE', 'Miembro del comité')], max_length=30),
        ),
    ]
