# Generated by Django 6.1.1 on 2026-09-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0008_alter_tutoringparticipant_rol_en_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='actividad_tipo',
            field=models.CharField(choices=[('TUTORIA', 'Tutoría'), ('ACUERDO', 'Acuerdo'), ('TESIS', 'Tesis'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=20),
        ),
    ]
