# Generated by Django 6.1.1 on 2026-09-15 01:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0009_alter_evidence_actividad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='fecha_carga',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
