# Generated by Django 6.1.1 on 2026-09-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0010_alter_evidence_fecha_carga'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(('actividad_tipo__in', ['TUTORIA', 'ACUERDO', 'TESIS', 'OTRO'])), name='evidence_valid_activity_type'),
        ),
    ]
