# Generated by Django 6.1 on 2026-09-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('fecha_limite', models.DateField(db_index=True, verbose_name='fecha límite')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('CONCLUIDO', 'Concluido'), ('VENCIDO', 'Vencido')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='estado')),
                ('fecha_conclusion', models.DateField(blank=True, null=True, verbose_name='fecha de conclusión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'acuerdo / compromiso',
                'verbose_name_plural': 'acuerdos y compromisos',
                'ordering': ['-fecha_limite', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgreementAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='estado anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='estado nuevo')),
                ('comentario', models.TextField(blank=True, default='', verbose_name='comentario')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='fecha de cambio')),
            ],
            options={
                'verbose_name': 'bitácora de cambio de estado de acuerdo',
                'verbose_name_plural': 'bitácoras de cambio de estado de acuerdos',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
